config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks do
    collection { post :sort}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order('position')
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(task_params)
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    params[:task].each_with_index do |id, index|
      Task.find(id).update_attribute(:position, index+1)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:text, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TaskManagement
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag :defaults, "rails.validations", "rails.validations.custom"
    /! Latest compiled and minified CSS
    link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet" /
    /! Optional theme
    link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" rel="stylesheet" /
    /! Latest compiled and minified JavaScript
    script crossorigin="anonymous" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
  body
    = yield

app/views/tasks/_form.html.slim
= form_for @task, :html => {:class => "form-inline"}, remote: true, validate: true do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message
  .form-group
    .field
      = f.text_field :text, class: "form-control task"
  .form-group
    .actions= f.button 'Add task', class: "btn btn-default"

app/views/tasks/_task.html.slim
li.list-group-item id="task_#{task.id}"
  = form_for task, remote: true do |f|
    = f.submit "Update"
    = f.label :complete, task.text
    = link_to "(remove)", task, method: :delete
    = f.check_box :complete, class: "pull-right"

app/views/tasks/create.js.slim
| $('#task_text').val('');
| $('#tasks').append("#{ j render @task}");
| $('#edit_task_#{@task.id}').submitOnCheck();

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

= link_to 'Show', @task
'  |
= link_to 'Back', tasks_path

app/views/tasks/index.html.slim
.container
  .row
    .col-md-10
      ul#tasks.list-group type="checkbox" data-update-url=sort_tasks_url
        - @tasks.each do |task|
          - if task.complete?
            li.list-group-item.complete-task id="task_#{task.id}"
              = form_for task, remote: true do |f|
                = f.submit "Update"
                = f.label :complete, task.text
                = link_to "(remove)", task, method: :delete
                = f.check_box :complete, class: "pull-right"
          - else
            li.list-group-item id="task_#{task.id}"
              = form_for task, remote: true do |f|
                = f.submit "Update"
                = f.label :complete, task.text
                = link_to "(remove)", task, method: :delete
                = f.check_box :complete, class: "pull-right"


      br
      == render 'form'

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Text:
  = @task.text

= link_to 'Edit', edit_task_path(@task)
'  |
= link_to 'Back', root_path

app/views/tasks/update.js.slim
| $('#task_#{@task.id}').toggleClass("complete-task");